version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: PromoAPI
    ports:
      - "27017:27017"

  promoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APSNETCORE_HTTPS_PORT=8080
      - APSNETCORE_HTTPS_PORT=8081
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promoAPI
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongodb